set WWISEPROJECTDIR=%1
set WWISEPROJECTFILE=%WWISEPROJECTDIR%\%2
set WWISEBUILDARGS=%3
set WWISEBUILDARGS=%WWISEBUILDARGS:"=%
set WWISESOUNDBANKSPATH=%WWISEPROJECTDIR%\GeneratedSoundBanks\
del /s /f /q %WWISESOUNDBANKSPATH%
"%WWISEROOT%\Authoring\x64\Release\bin\WwiseConsole.exe" generate-soundbank %WWISEPROJECTFILE% --no-source-control %WWISEBUILDARGS%
exit /B %ERRORLEVEL%